### ISSUE TITLE
issue with content variables

### ISSUE THREAD

**Issue by muxmix** [pulponair/koken-custom-meta-description#1]
When using content variables (like {{ page.content }}) the plugin reads html tags too.
This makes impossible to use content variables in meta description.

**Comment by pulponair** [comment]
Using variables is working in general. Please provide me with:
- koken version you are using
- theme you are using 
- what excactly you are trying to archieve and what exactly you get.

**Comment by muxmix** [comment]
Hallo,
I'm using latest version with elementary theme.
I tried to put {{ page.title }} - {{ page.content }} in page meta description and this is the meta tag resulting:
<meta name="description" content="Chi siamo - &lt;p class=" "="">
All the rest of the content appears in the page right after the opening body tag (see screenshot).
The problem is that since you plugin gets the html code, the meta tag ends after the p tag!

Thank you

Il giorno 08/giu/2014, alle ore 14:08, Nikolas Hagestein notifications@github.com ha scritto:

**Comment by pulponair** [comment]
This is not a bug. page.content contains the whole page content including markup code. If you want to use it as description you need to strip_html and might also want to truncate the text to it's first 160 characters: {{ page.content  strip_html="true"  truncate="160"}}
